{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "syft-generator-chart.fullname" . }}-role
  labels:
    {{- include "syft-generator-chart.labels" . | nindent 4 }}
rules:
{{ toYaml .Values.rbac.rules | indent 2 }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "syft-generator-chart.fullname" . }}-binding
  labels:
    {{- include "syft-generator-chart.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "syft-generator-chart.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "syft-generator-chart.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io
{{- end -}}
